# Generated by Django 5.2.5 on 2025-08-07 00:22
# Generated by Django 5.2.5 on 2025-08-07 00:08

from django.db import migrations
from decouple import config
from django.contrib.auth import get_user_model

def create_initial_record(apps, schema_editor):
    user_model = get_user_model()
    user_model.objects.create_superuser(
        email=config("INIT_EMAIL"), password=config("INIT_PASSWORD"),
    )

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_record),
    ]
