# Generated by Django 5.2.5 on 2025-08-07 00:08

from django.db import migrations

def create_initial_record(apps, schema_editor):
    garage_model = apps.get_model("parking", "Garages")
    garage_model.objects.create(
        name="slot1",
    )
    garage_model.objects.create(
        name="slot2",
    )
    garage_model.objects.create(
        name="slot3",
    )
    garage_model.objects.create(
        name="slot4",
    )
    garage_model.objects.create(
        name="slot5",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_record),
    ]
