# Generated by Django 5.2.5 on 2025-08-07 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20250807_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', related_query_name='reservation', to='parking.garages'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='plate',
            field=models.CharField(help_text='Name for the garage.', verbose_name='Name'),
        ),
    ]
