# Generated by Django 5.2.5 on 2025-08-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_reservation_garage_alter_reservation_plate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('garage', 'plate', 'day', 'start_time', 'end_time')},
        ),
    ]
