# Generated by Django 5.2.5 on 2025-08-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='amount_payed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='plate',
            field=models.CharField(help_text="Car's Plate.", verbose_name='Plate'),
        ),
    ]
